### PR TITLE
Add Yahoo Finance Provider

### PR DESCRIPTION
**Pull request by ghost**
# WIP

Adds the *very unofficial* Yahoo Finance API as a provider option. It has much more extensive data than what's provided by alphavantage or iexcloud.

---

Shout-out to mrtrev/MrTAP. :)

### CODE REVIEW

**Comment by ghost** [comment]
Just to expand: testing with both `alphavantage` and `iexcloud`. Just running `.stock tsla`, `.stock msft`, and similar yielded no errors or weird output.

**Comment by ghost** [comment]
I'm not sure how to put a PR "on hold" without just closing and resubmitting later, but this is on pause. Turns out [the GLOBAL_QUOTE endpoint](https://www.alphavantage.co/documentation/#latestprice) is not what @mrtrev actually wanted. 😜

I believe that [TIME_SERIES_INTRADAY](https://www.alphavantage.co/documentation/#intraday) or [TIME_SERIES_INTRADAY_EXTENDED](https://www.alphavantage.co/documentation/#intraday-extended) is probably what's wanted. Some minor adjustments will need to be made before submitting updated code.

**Comment by dgw** [comment]
> I'm not sure how to put a PR "on hold" without just closing and resubmitting later

[Convert it to draft](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request#converting-a-pull-request-to-a-draft).

**Comment by xnaas** [comment]
I suppose here is as good a place as any to ask this:

@dgw / @RustyBower / @Exirel: I've been playing with using the *very unofficial* Yahoo Finance API. They specifically block the default User-Agent sent by the requests module of Python. This is easily bypassed by adding a header that sets your User-Agent to literally anything else (that I tried, even insults, memes, and single letters).

What I want to know is y'all's stance on bypassing a clearly intentional block in an "official" Sopel plugin.

**Comment by ghost** [comment]
Neither myself nor the other party has any intention of finishing up or doing additional work on this PR. Closed.

**Pull request closed without merging**
